### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by bahiraei** [payam-zahedi/toastification#1]
This package is really great, thank you for the development
Please provide custom animations as well.
For example, a bouncing animation or slide from left or right

**Comment by payam-zahedi** [comment]
Hello @bahiraei  , thanks for your suggestion. We are going to have it in the next release. I'm trying to make it happen in the upcoming weeks.

**Comment by payam-zahedi** [comment]
Hey @bahiraei 
we have this possibility to add custom animation in our new version

for more information, take a look at example app and documentation


https://user-images.githubusercontent.com/47558577/231000100-78422b4c-fc41-434b-9107-da4a12f08459.mp4
