### ISSUE TITLE
Area behind toast is not clickable

### ISSUE THREAD

**Issue by Artur-Wisniewski** [payam-zahedi/toastification#100]
Hi! I have question regarding your package. Is it any way to have this area behind toast translucent? Now I am not able to click on back button because area behind notification is opaque. 

View example:
<img src="https://github.com/payam-zahedi/toastification/assets/46329000/7ded046d-e9c6-4268-87c0-abec83fdee59" width="300">

Code to reproduce:
```
toastification.showCustom(
      alignment: Alignment.topCenter,
      context: context,
      autoCloseDuration: const Duration(seconds: 5),
      builder: (context, holder) => Center(
        child: GestureDetector(
          onTap: () => toastification.dismiss(holder),
          child: Container(
            height: 40,
            width: 100,
            color: Colors.red,
          ),
        ),
      ),
    );
```

**Comment by payam-zahedi** [comment]
Can you also test it with the builder website?

https://payamzahedi.com/toastification/

**Comment by payam-zahedi** [comment]
https://github.com/payam-zahedi/toastification/assets/47558577/88ac32dc-8b83-4bf2-8d5c-882d2503dfe1

**Comment by Artur-Wisniewski** [comment]
On builder website it works very good, as expected 👍🏻

**Comment by Artur-Wisniewski** [comment]
But it still doesn't work for mobile applications. I found couple of thing. AnimationList inside overlay has additional padding. That's the blue field that is surrounding my red box. Also, second problem is this config. Width of item is not calculated? I didn't test it yet:
```
final config = ToastificationConfigProvider.maybeOf(context)?.config ??
        const ToastificationConfig();
```
