### ISSUE TITLE
Add max lines for title and message 

### ISSUE THREAD

**Issue by payam-zahedi** [payam-zahedi/toastification#105]
**Describe the bug**
It would be better for the UX to have a default max lines for title and description fields

Its better to have the default max lines with elips effect 

2 lines would be enough

**Screenshots**

![image](https://github.com/payam-zahedi/toastification/assets/47558577/e1fe278d-f6e2-47de-889f-63cf102f1f04)

**Comment by laterdayi** [comment]
Hope to follow up on this issue, thank you  https://github.com/payam-zahedi/toastification/issues/101

**Comment by DevTekoa** [comment]
Hello! Why not use this as a parameter?

**Comment by payam-zahedi** [comment]
Hello @DevTekoa,

Just to clarify, you can already control the `maxLines` parameter through the Text widgets that are being passed to the `title` and `description` fields. Given this functionality, introducing an additional parameter for line limits may not be necessary.
