### ISSUE TITLE
Add ability to disable title

### ISSUE THREAD

**Issue by idea-garage** [payam-zahedi/toastification#106]
It's so nice to disable title. Showing only body is more simple and smart.
Additionally, disabling icon is also good.

**Comment by payam-zahedi** [comment]
Can you send me some examples?

How it can be usefull? like some Images or so?

**Comment by idea-garage** [comment]
thank you. I just want to display her one line message like "Your order has been accepted." or "Your order has been cancelled."

**Comment by payam-zahedi** [comment]
@idea-garage 
Have tried the simple style?

**Comment by idea-garage** [comment]
Thanks for information. I hope simple toast to be colored, or with icon/ close button.

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi,

I believe this feature is already implemented. During my testing, I noticed that when creating a Toast with only a description (without a title), the description aligns correctly to the right.

**Comment by payam-zahedi** [comment]
@AntonioAEMartins 

I guess this issue is more about to add close button to simple toast widget
