### ISSUE TITLE
Add possibility to change clipBehaviour of AnimatedList

### ISSUE THREAD

**Issue by komakur** [payam-zahedi/toastification#107]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Either add new argument to config, or just change AnimatedLis.clipBehaviour to `clipBehavior: Clip.none` in toastification.manager.dart.

**Additional context**
If every item has a shadow, it will be clipped by AnimatedList, so I need to add padding to my item to fix this. Better solution would be to pass clipBehavior or just to 'disable' it. Thus, making clip behaviour none, increases performance.
It also quite useless to have clipbehavior with notifications as they should "float" anyway

![shadow is clipped](https://github.com/payam-zahedi/toastification/assets/78662639/a977b6f4-dd79-4287-965b-d05ccce07a56)
![image](https://github.com/payam-zahedi/toastification/assets/78662639/c66203cc-1fa5-4fd4-b011-0d53d6452cc9)
As you can see the shadow of items is being clipped.

And after I changed clipBehavior to none:
![after I change clipBehavior](https://github.com/payam-zahedi/toastification/assets/78662639/b552d1f2-301e-454c-a275-c33b254a2946)

**Comment by payam-zahedi** [comment]
Thanks @komakur 
Yes it will make sense 

In the next version, we will use `ClipBehavior.none` as default value

and also user will be able to set it through the Configuration

**Comment by payam-zahedi** [comment]
@komakur 

If you would like to work on it, please don't hesitate.

**Comment by komakur** [comment]
@payam-zahedi yeah, I can work on it
