### ISSUE TITLE
Problems encountered in using toastification

### ISSUE THREAD

**Issue by laterdayi** [payam-zahedi/toastification#109]
I have been using `bot_toast` before and I want to switch to `toastification`, but I encountered some problems, I hope the author can solve them

1. The animation is slow, it seems that the transition animation is very slow，I don't know if it's a performance issue or an animation transition issue
2. I will close all `toast` before displaying, but the animation position will be wrong
3. Blank display when clicked quickly
4. Supports the configuration style, width, height....

How should these problems be solved

@payam-zahedi

**Comment by laterdayi** [comment]
`bot_toast`

![Code_7HFzmaqaDQ](https://github.com/payam-zahedi/toastification/assets/122137647/d782b929-2161-49d2-8d3e-50240737392c)

`toastification`

![mobile_MzhoQ0LrOh](https://github.com/payam-zahedi/toastification/assets/122137647/79fc8a3f-1367-4a8d-9e4b-fde8fed419d1)

**Comment by laterdayi** [comment]
```
  void handle() {
    toastification.dismissAll();
    toastification.show(
      type: ToastificationType.error,
      style: ToastificationStyle.flatColored,
      title: const Text('Fail),
      alignment: Alignment.bottomCenter,
      showProgressBar: false,
      autoCloseDuration: const Duration(seconds: 4),
      animationBuilder: (
        context,
        c,
        alignment,
        child,
      ) {
        return Transform.translate(
          offset: Tween<Offset>(
            begin: const Offset(0, 40),
            end: const Offset(0, 0),
          ).evaluate(c),
          child: Transform.scale(
            scale: Tween<double>(begin: 0.7, end: 1.0).evaluate(c),
            child: Opacity(
              opacity: c.value,
              child: child,
            ),
          ),
        );
      },
    );
  }
```

**Comment by payam-zahedi** [comment]
I have to double check this issue

**Comment by laterdayi** [comment]
I reset the parameters, but the problem  1、2、3 persists

```
toastification.dismissAll(delayForAnimation: false);
    toastification.show(
      type: ToastificationType.error,
      style: ToastificationStyle.flatColored,
      title: const Text('Fail'),
      alignment: Alignment.bottomCenter,
      showProgressBar: false,
      autoCloseDuration: const Duration(seconds: 4),
      animationBuilder: (
        context,
        animation,
        alignment,
        child,
      ) {
        return Transform.translate(
          offset: Tween<Offset>(
            begin: const Offset(0, 40),
            end: const Offset(0, 0),
          ).evaluate(animation),
          child: Transform.scale(
            scale: Tween<double>(begin: 0.7, end: 1.0).evaluate(animation),
            child: Opacity(
              opacity: animation.value,
              child: child,
            ),
          ),
        );
      },
    );
```

**Comment by laterdayi** [comment]
https://github.com/payam-zahedi/toastification/assets/122137647/9b39e5c3-ed5c-40df-825a-afa8aaaf67d3


I re-summarized the problem

1. In the first second of the video, I double-clicked twice. Although I had set dismissAll(delayForAnimation: false), it still toasted twice.
2. 3-5 seconds into the video, I keep clicking but the toast animation is out of position
3. In the 6-8 seconds of the video, quick click does not close the animation, does not show the animation, and displays blank
4. Present on first click, The animation is slow, it seems that the transition animation is very slow, I don't know if it's a performance issue or an

**Comment by laterdayi** [comment]
https://github.com/payam-zahedi/toastification/assets/122137647/759a1f1e-3b84-4098-a772-078247666b06

This is about the first time the pop-up is slow, the first time is always slow, after the click is normal speed

**Comment by laterdayi** [comment]
Is there a plan to fix it?
  @payam-zahedi

**Comment by payam-zahedi** [comment]
Hey @laterdayi 
Basicly this is not a bug, 

It's a new feature that we have to add to the package

This is a feature that helps user to only show one toast in screen.

**Comment by payam-zahedi** [comment]
For now, I'm not sure most of the users need this.

So let's give it more time

**Comment by laterdayi** [comment]
This should be a series of side effects brought about by manually closing all, resulting in the inability to manually close all

**Comment by payam-zahedi** [comment]
Let me try it in this weekend to see how we can deal with it

**Comment by laterdayi** [comment]
Thanks for your help, looking forward to it

**Comment by Pluto1219** [comment]
> Let me try it in this weekend to see how we can deal with it


I feel that the author has provided such a good plug-in. At present, I feel that the toastification.show pop-up does have a delay of about 300 milliseconds. I hope the author can help us check it. Thank you very much.

**Comment by maxfrees** [comment]
any update @payam-zahedi
