### ISSUE TITLE
cannot interact with the area below toast

### ISSUE THREAD

**Issue by Yukari-Tryhard** [payam-zahedi/toastification#112]
**Describe the bug**
When showing notification there is a large space of padding (i think) that stop user from interacting on Android and iOS

**To Reproduce**
1. Create a bottom navigation
2. Create a toastification with alignment of bottomCenter
3. Try to click any of the navigation items

**Expected behavior**
User can still interact with the UI beneath notifcation

**Screenshots**
https://github.com/payam-zahedi/toastification/assets/61675970/7f67c55b-bd9c-4727-8943-73965d6ae7c4

**Flutter information:**
 - OS: [iOS, android]
 - Flutter Version: [3.22.1]
 - Toastification Version [2.0.0]

**Comment by Yukari-Tryhard** [comment]
@payam-zahedi  can you confirm this is a bug or it was intend to be like this

**Comment by sagnik-sanyal** [comment]
@payam-zahedi  @Yukari-Tryhard Yes i did encounter this problem, do you guys found out any solution to this ? Whenever the toast appears the section underneath cant be interacted with. Happens with me in the appbar backbutton .

**Comment by scharfschiesser** [comment]
@payam-zahedi This happens for me too and is a pretty high priority issue for mobile users. If you swipe to dismiss a toast before the duration is over, you cannot interact with the area that the toast was displayed over until the duration passes.

**Comment by payam-zahedi** [comment]
@scharfschiesser 

Yes, I will try to fix this as soon as possible

**Comment by ilyasarafathemvigo** [comment]
It is a high priority one. @payam-zahedi

**Comment by BenjiFarquhar** [comment]
I have this issue. I can't click on an action button in the top right, when my toast is displayed nowhere near it.

**Comment by payam-zahedi** [comment]
Hey Guys, 

I fixed this on the newest version.

Please take a look and let me know if you still have the same problem.

**Comment by payam-zahedi** [comment]
I'll close this for now, but feel free to reopen it.
