### ISSUE TITLE
Single Toast at one time.

### ISSUE THREAD

**Issue by uday-jploft** [payam-zahedi/toastification#113]
**When multiple toast notifications appear on the web, there is enough space to show them. However, in a mobile app, if multiple toasts appear before the last one closes, they cover the entire mobile screen and negatively impact the user experience. I need help as a developer to be able to switch the notifications one by one instead of in a queue, and also switch back to the queue mode.**

**Comment by bwcr** [comment]
Having multiple notifications appear at a time on a mobile can be burdensome. Providing an option to limit the notifications shown is a great idea.

**Comment by alirezat66** [comment]
@payam-zahedi  I will do it as next version

**Comment by payam-zahedi** [comment]
@alirezat66 Awesome. I'm looking into it

**Comment by AntonioAEMartins** [comment]
Good morning @alirezat66 any updates?

If you want I can help you with the implementation.
