### ISSUE TITLE
There is a UI bug in Builder web page (https://payamzahedi.com/toastification)

### ISSUE THREAD

**Issue by P-B1101** [payam-zahedi/toastification#117]
**Describe the bug**
In the builder website at the Controllers and Interactions section, in animation type dropdown when you select Slide in/out in options, scale animation will apply.

**To Reproduce**
1. Go to [Toastification](https://payamzahedi.com/toastification).
2. Scroll down to Controllers and Interaction.
4. Select Slide in/out in animation type.
5. see scale transition in code box.

**Expected behavior**
apply Slide in/out transition

**Screenshots**
![Capture](https://github.com/user-attachments/assets/ef7cc448-824c-421c-9a25-2fa80f8921c4)

**Comment by payam-zahedi** [comment]
Hey @P-B1101 

You are right, we might need to only change the animation type title 

from Slide in/out to Scale in/Out
