### ISSUE TITLE
Ability to change close Icon button with custom widget (Text Widget)

### ISSUE THREAD

**Issue by ilyasarafathemvigo** [payam-zahedi/toastification#118]
![Screenshot_1722513539](https://github.com/user-attachments/assets/0c5ec87c-916a-4b18-ad56-7b5ffdc5b3b4)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by niklasbartsch** [comment]
Hey you can just create your custom toast:
https://pub.dev/packages/toastification#showcustom-method

**Comment by ilyasarafathemvigo** [comment]
@niklasbartsch  Thank you for your support, closing this ticket
