### ISSUE TITLE
Cannot hide the icon if the style is FlatColored

### ISSUE THREAD

**Issue by sandunrajitha** [payam-zahedi/toastification#121]
**Describe the bug**
I tried to hide the icon by setting `showIcon: false` and the style to `ToastificationStyle.flatColored `
But the toast still shows the default icon. But I can hide the icon successfully for other styles.

**To Reproduce**
1. Go to https://payamzahedi.com/toastification/
2. Set the style to `ToastificationStyle.flatColored`
3. Set `showIcon: false`
4. And preview on screen

**Expected behavior**
Icon should be hidden.

**Screenshots**
<img width="1386" alt="Screenshot 2024-08-09 at 4 41 31 PM" src="https://github.com/user-attachments/assets/5ca2fac8-8f14-41f5-94b8-fd2a7a54f9f7">

**Flutter information:**
 - OS: iOS, MacOS
 - Flutter Version: 3.22.2
 - Toastification Version 2.1.0

**Comment by payam-zahedi** [comment]
Hey @sandunrajitha 

Thanks for opening this issue, Yes you are right. 

we can fix it in the next version.

Also, if you are interested, you can take a look at it and try to fix it.

**Comment by sandunrajitha** [comment]
@payam-zahedi Thank you fro the quick reply. 
Let me try to do it over this weekend.
