### ISSUE TITLE
Raising the top of toast with the keyboard open

### ISSUE THREAD

**Issue by StarProxima** [payam-zahedi/toastification#124]
@payam-zahedi Thanks for a great package, the quality level is really very high, I am in the process of switching from my own solution to this package.

**Describe the bug**

Currently, toasts do not react to an open keyboard, so the user can skip them when acting while the keyboard is still open.

Video demonstrating the problem:

https://github.com/user-attachments/assets/c44c1756-580d-4f18-ae4f-cc03c488865c

**Expected behavior**
Toasts go up over the keyboard when it is open and down when it is closed.
Perhaps we could add an additional parameter to regulate this behavior.

**Flutter information:**
 - OS: android
 - Flutter Version: 3.24.0
 - Toastification Version 2.1.0

**Comment by payam-zahedi** [comment]
Hey @StarProxima 

Thanks for opening the issue

Yes, I didn't think about this and this must be solved ASAP.

**Comment by payam-zahedi** [comment]
If you are looking for a quick solution for now, I would suggest changing the alignment of your toasts

You can show them from top.

**Comment by ghrlt** [comment]
> Here's my workaround:
> 
> Add `MediaQuery.of(context).viewInsets.bottom` as the toast padding.
> 
Is there a workaround if we have **no context** available?
