### ISSUE TITLE
Can't interact with area below toast

### ISSUE THREAD

**Issue by mark1saeid** [payam-zahedi/toastification#127]
Describe the bug
When showing notification there is a large space of padding (i think) that stop user from interacting on Android and iOS

To Reproduce

Create a bottom navigation
Create a toastification with alignment of bottomCenter
Try to click any of the navigation items
Expected behavior
User can still interact with the UI beneath notifcation

Screenshots
https://github.com/payam-zahedi/toastification/assets/61675970/7f67c55b-bd9c-4727-8943-73965d6ae7c4

Flutter information:

OS: [iOS, android]
Flutter Version: [3.22.1]
Toastification Version [2.0.0]

**Comment by payam-zahedi** [comment]
Hey @mark1saeid 

Thanks for openning this issue 

I fixed it in #128 this PR.

You can try it in the new version and let me know if you still have this problem

**Comment by mark1saeid** [comment]
It still same issue 
when i make the toast on bottom center
when i press on the area on the bottom of the toast it not clickable or any action occurred 
@payam-zahedi

**Comment by payam-zahedi** [comment]
Could you please send some video

**Comment by mark1saeid** [comment]
[Uploading screen-capture (1).webm…]()

**Comment by mark1saeid** [comment]
https://jmp.sh/s/tnTkDidRBj3k3FYWQc0w

@payam-zahedi

**Comment by mark1saeid** [comment]
Thank you for your support

**Comment by payam-zahedi** [comment]
Alright @mark1saeid 

I will try to reproduce this

**Comment by ilyasarafathemvigo** [comment]
Same issue

**Comment by mark1saeid** [comment]
any update

**Comment by mark1saeid** [comment]
@payam-zahedi please tell me if you have fixed this bug

**Comment by payam-zahedi** [comment]
@mark1saeid 

Not yet, 

Perhaps in this weekend, I will work on it.
There are some edge cases here that we need to test them

For example: if the user shows a toast and open the keyboard, we need to move the toast to the above of the keyboard

**Comment by payam-zahedi** [comment]
@mark1saeid @ilyasarafathemvigo

I've addressed the issue in PR #135 

In the attached video, I demonstrate how the Toastification overlay behaves after the applied changes.

To clarify, the gray area behind the toasts remains untouchable, as it represents the placeholder for the toasts. However, the rest of the screen is fully interactive. I've also made adjustments to reduce the margin and padding around the toasts, providing more usable space for interaction.

Please let me know if any further adjustments are needed.


https://github.com/user-attachments/assets/875059e7-a7fe-4d40-9451-02b9361e2b7a
