### ISSUE TITLE
خطا در موقع بسته شدن دیالوگ

### ISSUE THREAD

**Issue by rezadevelopers2** [payam-zahedi/toastification#13]
سلام بعضی وقتا بعد از بسته شدن دیالوگ این خطا میاد

> Error: AnimationController.dispose() called more than once.
A given AnimationController cannot be disposed more than once.
The following AnimationController object was disposed multiple times:
  AnimationController#43e36(⏮ 0.000; paused; DISPOSED)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_

داخل نسخه وب

> [√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
    • Flutter version 3.10.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (9 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

**Comment by payam-zahedi** [comment]
سلام  ممنون از ایشو یی که زدی 
حتما بررسی میکنم و بهت خبر میدم دمت گرم

**Comment by payam-zahedi** [comment]
Since we have the V1.0.0 you shouldn't get this error anymore
