### ISSUE TITLE
How to set the maximum number of lines in the title or description?

### ISSUE THREAD

**Issue by thorito** [payam-zahedi/toastification#140]
In the last update toastification: ^2.3.0 the limit on the maximum number of lines was introduced.

How can I set a different value?

Thanks

**Comment by thorito** [comment]
Sorry, I just figured it out.

**Comment by Hesamedin** [comment]
@thorito What did you do? Tostification truncates my message and displays max two lines. 
My message needs more lines to be fully visible.

**Comment by thorito** [comment]
> Hesamedin

In title or description, in my example:

```dart
   toastification.show(
        context: this,
       ...
        description: description.isNotNullOrNotEmpty
            ? Text(
                description!,
                style: TextStyle(color: color),
                overflow: TextOverflow.ellipsis,
                maxLines: 5,
              )
            : null,
       ...
```

I hope it works for you
