### ISSUE TITLE
Support vertical drag to close

### ISSUE THREAD

**Issue by optdxf** [payam-zahedi/toastification#141]
Currently, dragToClose only allows you to drag left or right to close a toast. For toasts that have topCenter or bottomCenter alignment, vertical drag to close is intuitive/natural: there should be an option to allow you to allow for vertical drag to close in addition to horizontal drag to close.

A lot of mobile apps that allow for in-app notifications (via toasts) often allow you to vertically drag the notification to dismiss it. 

More broadly speaking: maybe it'd be nice to allow the developer to customize and decide whether they want vertical drag to close, horizontal, or both?

**Comment by payam-zahedi** [comment]
Hello @optdxf,

Just to let you know, you already have control over how the toast is dismissed by using the `DismissDirection? dismissDirection` parameter. This allows you to customize the dismissal direction, including vertical and horizontal, to achieve the behavior you're looking for.

**Comment by optdxf** [comment]
re: @payam-zahedi 

Oops, didn't know that existed! Thank you!
