### ISSUE TITLE
adding dragToClose variable for showCustom function

### ISSUE THREAD

**Issue by berk-can** [payam-zahedi/toastification#142]
**Is your feature request related to a problem? Please describe.**
I cannot use dragToClose variable when I'm using showCustom method

**Describe the solution you'd like**
dragToClose variable can be added  to showCustom method

**Comment by payam-zahedi** [comment]
Hi @berk-can,

Thank you for your suggestion!

While I understand your perspective, I believe that this behavior might not align with the preferences of the majority of users. However, what we can do is make the `BuiltInContainer` class public, allowing developers to utilize it directly. This way, they can wrap their custom widgets within it and take advantage of the drag-to-close feature and other functionalities.

Let me know your thoughts on this!


https://github.com/payam-zahedi/toastification/blob/953f938ecb693be6ec9c6f1df960cf75d2b89f5d/lib/src/widget/built_in/built_in_builder.dart#L367

**Comment by berk-can** [comment]
Hi thanks for response, while looking to library I figured that I can use show function with changing type to simple and giving my custom widget to title with zero padding margin etc. so actually library support showing custom widget with functionalities in show function. Thats why this subject was not a problem for me to begin with. Thank you for library have a good day
