### ISSUE TITLE
Custom Close Button

### ISSUE THREAD

**Issue by augustobalzanelli** [payam-zahedi/toastification#146]
Would be nice to instead of having a ToastCloseButton, a ToastButton, where I could set a label and an onPressed action on it. I tried using callbacks, but it did not achieve a good result and perfomance, also, I wanted to remove the close icon, to avoid dismissing the toastification by taps on it.

**Comment by payam-zahedi** [comment]
Hi @augustobalzanelli,

Thank you for your suggestion — it's a great idea!

To ensure that I fully understand your request, could you please provide an image or diagram illustrating exactly what you have in mind?

Looking forward to your response.

**Comment by augustobalzanelli** [comment]
Sure, something as this:
![image](https://github.com/user-attachments/assets/0a1b5b02-ef2b-443e-912f-a52f0beeccfb)

![image](https://github.com/user-attachments/assets/e851faba-d565-410d-a901-ad2235ee73a5)

Don't know exactly the design, but anything that could allow me doing something similar would be great.

**Comment by augustobalzanelli** [comment]
Hey @payam-zahedi,

Would you like some help on creating this? I've forked the repository and created a demo of the idea. You could keep reviewing the code and the widget and guiding me to achieve the ideal result.

You can review the code [here](https://github.com/augustobalzanelli/toastification).

Looking forward to your response. :)

**Comment by payam-zahedi** [comment]
Yes for sure @augustobalzanelli 

Thanks for working on it 

I would say to make it eazier for me you can just Create a Pull Request

and I can review it

**Comment by payam-zahedi** [comment]
Ideal approach would be to have a Widget parameter for close button so users can pass it to toastification as they want

**Comment by augustobalzanelli** [comment]
Right, I'm gonna start making the changes as you said and create the pull request later. 

See you!

**Comment by payam-zahedi** [comment]
Thanks @augustobalzanelli 

I'm looking forward to it

**Comment by reza00farjam** [comment]
Hi @payam-zahedi,

Thank you for creating this amazing package!

I wanted to highlight that this issue also affects projects that don't utilize Material icons (i.e., when `uses-material-design` is set to `false` in the project pubspec file). In such cases, the close icon appears like this:

![Screenshot](https://github.com/user-attachments/assets/e0d262b0-ee4c-479c-8cc8-64d3ea11b1b8)
