### ISSUE TITLE
Removing the close button's space after setting closeButtonShowType to none

### ISSUE THREAD

**Issue by Nicholastx96** [payam-zahedi/toastification#152]
Is there a way to remove the invisible space of the close button when you set closeButtonShowType to none when using .show?
It causes my descriptions to break into a new line due to the invisible space of the close button.

**Comment by payam-zahedi** [comment]
Hi @Nicholastx96, thank you for bringing this issue to our attention.

We've addressed it in PR #151 , and the fix will be included in the upcoming release.

Thanks again for your feedback!
