### ISSUE TITLE
Full message not showing. Please add auto width feature.

### ISSUE THREAD

**Issue by princeubxty** [payam-zahedi/toastification#160]
![image](https://github.com/user-attachments/assets/c99e163c-990d-406c-9f11-b6c5e536e622)

**Comment by payam-zahedi** [comment]
Hello @princeubxty,

Could you please share a code example of how you're implementing this? Specifically, how are you displaying the Toast? This will help us accurately reproduce and address the issue.

Thank you!

**Comment by NikitaSharapov** [comment]
+1 
`toastification.show(
      margin: const EdgeInsets.all(2),
      type: ToastificationType.info,
      style: ToastificationStyle.simple,
      title: Text(
        message,
        style: const TextStyle(
            height: 1,
            fontWeight: FontWeight.w600,
            fontSize: 12,
            color: Colors.white),
      ),
      borderRadius: const BorderRadius.all(Radius.circular(8)),
      borderSide: const BorderSide(color: Color.fromRGBO(75, 78, 81, 1)),
      backgroundColor: const Color.fromRGBO(75, 78, 81, 1),
      padding: const EdgeInsets.only(top: 10, bottom: 10, left: 16, right: 16),
      alignment: Alignment.bottomCenter,
      autoCloseDuration: const Duration(seconds: 4),
      animationBuilder: (
        context,
        animation,
        alignment,
        child,
      ) {
        return FadeTransition(
          opacity: animation,
          child: child,
        );
      },
      boxShadow: lowModeShadow,
      closeOnClick: false,
      dragToClose: true,
      pauseOnHover: false,
      showIcon: false,
    );`

**Comment by NikitaSharapov** [comment]
btw max line titel text property fix my problem, this is how it should be?

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi ,

I'm not entirely sure I understand the problem in terms of the code implementation. Could you provide a bit more clarification or context? This will help me better address and resolve the issue.

**Comment by payam-zahedi** [comment]
In the most recent version, the default maximum number of lines for the title was set to one. 
https://github.com/payam-zahedi/toastification/blob/e97c3ce6abcacd66460a6a78d7c5bf5610998545/lib/src/widget/built_in/built_in.dart#L47

However, I understand that this change might not align with the expectations of most users.

To improve this, I plan to increase the limit to two lines and add TextOverflow.ellipsis to handle longer titles gracefully.
