### ISSUE TITLE
Iconsax Dependency can be avoided

### ISSUE THREAD

**Issue by alangautham** [payam-zahedi/toastification#161]
**Is your feature request related to a problem? Please describe.**
Iconsax Dependency outdated

**Describe the solution you'd like**
Use a inbuilt icons only and leave upto users for better performance

**Describe alternatives you've considered**
Use a inbuilt icons only and leave upto users for better performance

**Additional context**

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi,

What are your thoughts on this topic? I’ve been reviewing the code, and it seems feasible to eliminate this dependency by switching to the default Material Icons. However, I’ve noticed that not all the icons match exactly or maintain the same style.

**Comment by payam-zahedi** [comment]
@AntonioAEMartins @alangautham

Iconsax is a package I optimized by converting it to a font system, which I believe will not cause any performance issues. Additionally, you have the flexibility to use your own icons with the show method. If you are using a custom icon package and not utilizing Iconsax, Dart's tree-shaking will remove any unused code related to it.

Finally, I want to emphasize that our icons are part of our design system, thoughtfully designed by Sepideh to ensure consistency and alignment with our visual identity.
