### ISSUE TITLE
Custom alignment and position for toasts

### ISSUE THREAD

**Issue by mahmoud-eslami** [payam-zahedi/toastification#31]
## Question
First, thank you for this great package.
I would like to change the alignment of the toast messages. Is there a built-in feature to do this?
According to the documentation, we can create our own custom toast with `showCustom()`. I tried that, but I was unable to change the position of the toast messages.
I think this feature would be useful, especially on wide devices or on the web platform.

Is it possible to show the toast at these positions ?

<img width="1280" alt=" " src="https://github.com/payam-zahedi/toastification/assets/57481226/9bbb505c-7ed5-492d-9b67-1d380ee81122">

**Comment by payam-zahedi** [comment]
I assume you are using v0.0.3? Is that right?

If yes, I should say it's not possible in that version. 

However, we are working to provide v1 of this package, in that version you can easily align your toast.

For now, I suggest getting the package from [git resource](https://dart.dev/tools/pub/dependencies#git-packages).

**Comment by payam-zahedi** [comment]
V1.0.0 is out, so you can easily use alignment feature.

I will close this issue, but if you have any other questions fell free to make it open again
