### ISSUE TITLE
A simple toast and toastification can be without context.

### ISSUE THREAD

**Issue by rvndsngwn** [payam-zahedi/toastification#51]
1. Simple toast like this:

`toast('Hello world!');`

https://github.com/payam-zahedi/toastification/assets/59143934/67edde36-db52-4b39-bc5a-dc5e4a605cf3

2. The toastification of without context:

```
toastification.show(
	  type: ToastificationType.success,
	  style: ToastificationStyle.flat,
	  title: 'Component updates available.',
	  description: 'Component updates available.',
	  alignment: Alignment.topLeft,
	  autoCloseDuration: const Duration(seconds: 4),
	);
```

**Comment by payam-zahedi** [comment]
So you have two requests

1. Simple text toast 
2. Show toasts with out using context

I'll work on your first request in future versions

But for the second request, I'm not sure is it possible or not
Because we are using navigator and to use navigator you need to have a context or navigator key

**Comment by callmephil** [comment]
> Show toasts without using context
> But for the second request, I'm not sure if it is possible or not Because we are using Navigator and to use Navigator you need to have a context or navigator key

Solution 1: Perhaps a simple solution would be to pass that context from the builder method on MaterialApp init and save it globally on Toast init.
Solution 2: Another one would be to extend the ScaffoldMessenger class provided by Flutter. Similar to MaterialBanner or Snackbar.
Usage: 
```dart
void showToastWithoutContext() {
// Create and set rootNavigatorKey to your router config and grab the context.
final context = rootNavigatorKey.currentContext;
ScaffoldMessenger.of(context).showToast(...);
}
```

**Comment by payam-zahedi** [comment]
We have the simple toast in this new version (v1.1.0) 

you can use the `ToastificationStyle.simple` as your toast style

**Comment by laterdayi** [comment]
If the second request has a progress plan, many people will need it

**Comment by payam-zahedi** [comment]
Hey @laterdayi 

I'm planning to achieve this in the next major release.

But, I can't give an exact date.
