### ISSUE TITLE
Loading style toast

### ISSUE THREAD

**Issue by laterdayi** [payam-zahedi/toastification#56]
Only text or loading is supported

**Comment by laterdayi** [comment]
sorry, there is something wrong with my description. Can I support the display of only text and loading

![图片](https://github.com/payam-zahedi/toastification/assets/122137647/937e185e-967e-4ddf-88e7-30f1342aeae9)

![图片](https://github.com/payam-zahedi/toastification/assets/122137647/7eb5858e-311b-409b-bd52-20cf5ee70c41)

**Comment by laterdayi** [comment]
Can it be top-level injected like bot toast, so you don't need to provide context where you use it

@payam-zahedi

**Comment by payam-zahedi** [comment]
We have the simple toast in this new version (v1.1.0) 

you can use the `ToastificationStyle.simple` as your toast style

**Comment by payam-zahedi** [comment]
Duplicated #68
