### ISSUE TITLE
Callback for AutoComplete Completion

### ISSUE THREAD

**Issue by Shery573** [payam-zahedi/toastification#58]
I was recently working on a project and I needed to run a callback when the the autocomplete duration was completed.
So I forked the project and saw it was relatively simple change that I just had to expose to the show() method. Can we implement this. I could work on this if you like.

**Comment by payam-zahedi** [comment]
Hey @Shery573 

Yes, that's a good Idea

I would be awesome if you could work on it

**Comment by payam-zahedi** [comment]
Fixed in #59
