### ISSUE TITLE
onTap on the whole toast is missing

### ISSUE THREAD

**Issue by Ahmadre** [payam-zahedi/toastification#63]
It would be great to have a onTap Callback, when users tap on the toast itself.

This way you can interact by for example pushing into a route or handling data that came with a Push-Notification for example :).

> Note: I don't want to use the `builder` method and make my own Widget just to have an `onTap`. It would be great to provide this :)

**Comment by Ahmadre** [comment]
A workaround now would be:

```dart
toastification.showCustom(
              context: context,
              autoCloseDuration: const Duration(seconds: 5),
              builder: (context, holder) => GestureDetector(
                onTap: () {
                  context.go(message.data['route']!);
                },
                child: BuiltInBuilder(
                  item: holder,
                  title: notification?.title ?? '',
                  description: notification?.body,
                  type: ToastificationType.info,
                  style: ToastificationStyle.flat,
                ),
              ),
            );
```

**Comment by payam-zahedi** [comment]
Hey @Ahmadre 
Yes, This is a greate Idea

I'll work on it in the release

**Comment by Ahmadre** [comment]
> Hey @Ahmadre 
> 
> Yes, This is a greate Idea
> 
> 
> 
> I'll work on it in the release
> 
> 

Thanks :) and greetings from Neofight and me ;) we use your package for an eHealth App coming soon :)

**Comment by payam-zahedi** [comment]
I'm thrilled to hear that you like it! Your support means the world to me. Best of luck with your eHealth App - Can't wait to see what you're cooking up 🌟😄

**Comment by payam-zahedi** [comment]
So @Ahmadre 
I just published a new version, in this version you can pass a set of callbacks to your toast with [ToastificationCallbacks ](https://github.com/payam-zahedi/toastification/blob/main/lib/src/core/toastification_callbacks.dart) class.

**Comment by imaNNeo** [comment]
Thank you, Payam :)
We will let you know about the app we are working on later
Keep it up bro

**Comment by payam-zahedi** [comment]
Thanks @imaNNeo for your support
