### ISSUE TITLE
An example of adding loading to a sample website

### ISSUE THREAD

**Issue by laterdayi** [payam-zahedi/toastification#68]
An example of adding loading to a sample website

**Comment by payam-zahedi** [comment]
Hey @laterdayi 

Do you want something like this?

![276504679-7eb5858e-311b-409b-bd52-20cf5ee70c41](https://github.com/payam-zahedi/toastification/assets/47558577/ac3adade-b709-49c7-93ce-5dbcd59929fc)

**Comment by laterdayi** [comment]
@payam-zahedi  HI ， Yes, looking forward to such a feature

**Comment by payam-zahedi** [comment]
Actually, you can create something like this with `showCustom` method.

check out this code:

``` dart

  toastification.showCustom(
    context: context,
    alignment: toastDetail.alignment,
    builder: (context, holder) {
      return Container(
        width: 100,
        height: 100,
        decoration: BoxDecoration(
          color: Colors.black26,
          borderRadius: BorderRadius.circular(24),
        ),
        child: const Center(child: CircularProgressIndicator()),
      );
    },
```

**Comment by payam-zahedi** [comment]
I will close this for now. But, you can open it whenever you find it necessary.
