### ISSUE TITLE
Dispose/Close all the notifications

### ISSUE THREAD

**Issue by RoyalCoder88** [payam-zahedi/toastification#69]
Hi @payam-zahedi ,

First thanks a lot for your amazing package!

I'm wondering if it's possible to dispose/close all the showing notifications when we're navigating to another widget page, or to close all of them programmatically somehow via controller or other ways?
I think this will be an amazing feature! 

Thanks in advance!

**Comment by laterdayi** [comment]
Whether you can provide a closeAll() function

**Comment by RoyalCoder88** [comment]
@laterdayi how?

**Comment by payam-zahedi** [comment]
If you want to close all the toasts programmatically, you can use `dismissAll` function.

``` Dart
toastification.dismissAll();
```

Source:
https://github.com/payam-zahedi/toastification/blob/c96b7318e90478e77a63b4638dd33dea416ee6d9/lib/src/core/toastification.dart#L315

**Comment by payam-zahedi** [comment]
@RoyalCoder88 
is that what you want?
