### ISSUE TITLE
DragToClose vertical direction

### ISSUE THREAD

**Issue by sergiyvergun** [payam-zahedi/toastification#71]
It would be great if the package would support dragging to close in the vertical direction. So if toast is shown from the top it will be possible to drag not horizontally but to the top.

**Comment by payam-zahedi** [comment]
Hey @sergiyvergun 

Thank you for opening this issue.

This is a good Idea, I will try to add it for the next release

**Comment by payam-zahedi** [comment]
We fixed this in #83 PR 

So you will be able to use it in the next version
