### ISSUE TITLE
Save the latest state of the toast builter site - keep the user last state

### ISSUE THREAD

**Issue by payam-zahedi** [payam-zahedi/toastification#73]

**Comment by AntonioAEMartins** [comment]
@payam-zahedi Can you explain better what is the need in this issue?

**Comment by payam-zahedi** [comment]
Hi again, @AntonioAEMartins,

Thank you for your interest in contributing to this package! I truly appreciate your willingness to help.


To give you some context:

Imagine you visit the Toastification website, make some changes, and copy the code to use in your project. But if you close the browser and return later, you won't see the changes you made—they're not saved.

The goal of this task is to store and save the state of the website, so that when you come back, your last settings or changes are still there.
