### ISSUE TITLE
Website: Color Picker Component

### ISSUE THREAD

**Issue by payam-zahedi** [payam-zahedi/toastification#74]
We need to implement the Color picker in our [toast builder website](https://payamzahedi.com/toastification/). 

![image](https://github.com/payam-zahedi/toastification/assets/47558577/d92d541c-52ad-4a31-a905-a8b1d70e8363)

**Comment by mahmoud-eslami** [comment]
Hi Payam, I'm interested in contributing to this feature. Could you please let me know if someone else is already working on it or not?

**Comment by payam-zahedi** [comment]
Hey @mahmoud-eslami 

Thanks for your proposal
Yes, you can start working on it.

I will assign it to you.

**Comment by payam-zahedi** [comment]
It would be awesome if we could achieve something like this in a dialog.

![image](https://github.com/payam-zahedi/toastification/assets/47558577/6a993ef3-2886-4962-b9eb-19c040a9e5a4)
