### ISSUE TITLE
Custom animation: how to set the animation of toast closing?

### ISSUE THREAD

**Issue by disonwei** [payam-zahedi/toastification#75]
toastification.show(
      context: context,
      type: ToastificationType.success,
      style: ToastificationStyle.fillColored,
      title: title,
      description: description,
      alignment: Alignment.topCenter,
      autoCloseDuration: const Duration(seconds: 3),
      // animationDuration: const Duration(milliseconds: 400),
      animationBuilder: (
        context,
        animation,
        alignment,
        child,
      ) {
        return TweenAnimationBuilder(
          tween: Tween(begin: Offset(0.0, -1.0), end: Offset(0.0, 0.0)),
          duration: Duration(milliseconds: 700),
          curve: Curves.elasticOut,
          builder: (context, offset, child) {
            return FractionalTranslation(
              translation: offset,
              child: child,
            );
          },
          child: child,
        );
      },
      borderRadius: BorderRadius.circular(40.0),
      boxShadow: highModeShadow,
      // primaryColor:Colors.deepPurpleAccent,
      // backgroundColor:Colors.red.withOpacity(0.2),
      // foregroundColor:Colors.teal,
      // dragToClose: true,
    );

I used the above code to implement a bounce animation, but I found that when autoclose, the component moved up halfway and disappeared. And no animation effect. I want the effect of sliding up to slide out of the screen when the component disappears, or the effect of gradual disappearance. How to achieve?

**Comment by payam-zahedi** [comment]
For the custom animations, you need to use the `animation` parameter provided by the function.
For example, if you want to implement the slide transition, you can use this example:

```dart
        toastification.show(
          context: context,
          type: ToastificationType.success,
          style: ToastificationStyle.fillColored,
          title: Text('title'),
          alignment: Alignment.topCenter,
          autoCloseDuration: const Duration(seconds: 3),
          // animationDuration: const Duration(milliseconds: 400),
          animationBuilder: (
            context,
            animation,
            alignment,
            child,
          ) {
            return SlideTransition(
                position: Tween(begin: Offset(0, -1), end: Offset(0, 0))
                    .animate(animation),
                child: child);
          },
          borderRadius: BorderRadius.circular(40.0),
          boxShadow: highModeShadow,
        );

```

**Comment by payam-zahedi** [comment]
I'll close this issue for now 

but feel free to reopen it
