### ISSUE TITLE
Get.context  Unhandled Exception: No Overlay widget found. 

### ISSUE THREAD

**Issue by disonwei** [payam-zahedi/toastification#76]
**Describe the bug**
I am using getx.

    toastification.showCustom(
      context: context,
      autoCloseDuration: const Duration(seconds: 5),
      alignment: alignment ?? Alignment.topCenter,
      animationDuration: Duration(milliseconds: 400),
      builder: (BuildContext context, ToastificationItem holder) {
        return child;
      },
    );

showCustom need to provide a context paramete. 

I used the Get.context in getx!, But it reported wrong.

E/flutter (20377): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
E/flutter (20377): Some widgets require an Overlay widget ancestor for correct operation.
E/flutter (20377): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
E/flutter (20377): The context from which that widget was searching for an overlay was:
E/flutter (20377):   Navigator-[LabeledGlobalKey<NavigatorState>#7a7dd Key Created by default]
E/flutter (20377): #0      Overlay.of.<anonymous closure> (package:flutter/src/widgets/overlay.dart:487:9)
E/flutter (20377): #1      Overlay.of (package:flutter/src/widgets/overlay.dart:490:6)
E/flutter (20377): #2      ToastificationManager._createNotificationHolder (package:toastification/src/core/toastification_manager.dart:192:45)
E/flutter (20377): #3      ToastificationManager.showCustom (package:toastification/src/core/toastification_manager.dart:59:7)
E/flutter (20377): #4      Toastification.showCustom (package:toastification/src/core/toastification.dart:138:20)
E/flutter (20377): #5      CustomToast._commonCustom (package:share_cards_flutter/shared/util/ToastUtil.dart:94:20)
E/flutter (20377): #6      CustomToast.showStatusSuccess (package:share_cards_flutter/shared/util/ToastUtil.dart:132:5)
E/flutter (20377): #7      PictureCardController.saveImgToGallery (package:share_cards_flutter/app/modules/picture_card/controllers/picture_card_controller.dart:164:19)
E/flutter (20377): <asynchronous suspension>

My Main method is as follows：

class AppMain extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "ShareCards",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
    );
  }
}

**Comment by payam-zahedi** [comment]
Hi @disonwei 
I'm not a GetX user, so I'm not sure about this issue.

But I think you can send a navigator key to GetMaterialApp and use that to get the overlay context.

https://github.com/jonataslaw/getx/blob/499b4a2be24a3cc6c19845573b56e37f66f33ca4/lib/get_navigation/src/root/get_material_app.dart#L10

and you can use the navigator key to get the context like this:

``` dart 
    final context = navigatorKey.currentState.context;
```

**Comment by NavidHosseini** [comment]
@disonwei just use 

BuildContext context = Get.overlayContext!;
