### ISSUE TITLE
ValueNotifier<ToastTimeStatus> not disposed

### ISSUE THREAD

**Issue by dorklein** [payam-zahedi/toastification#90]
**Describe the bug**
I get this bug in multiple places in my app after calling toastification.show
```dart
ValueNotifier<ToastTimeStatus> not disposed
```

**Expected behavior**

**Flutter information:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
[✓] Network resources

 - Toastification Version: 1.2.1

**Additional context**

**Comment by payam-zahedi** [comment]
Hey @dorklein 

Thanks for opening this issue

Can you send me more information like Stacktrace or something?

**Comment by payam-zahedi** [comment]
@dorklein 
Can you please send more info on this?

**Comment by payam-zahedi** [comment]
I will close this for now 

But feel free to open it if you still have this issue
