### ISSUE TITLE
feat: adaptable size for different screen sizes

### ISSUE THREAD

**Issue by tomassasovsky** [payam-zahedi/toastification#91]
**Is your feature request related to a problem? Please describe.**
The following image is an example of the notification on an Android foldable device (1768x2208 px).
![Screenshot_1709260405](https://github.com/payam-zahedi/toastification/assets/63405252/7fc294ff-036a-462a-8159-4a4d50b837cc)

**Describe the solution you'd like**
I would like the notification to be wider, or for the size of the notification itself to be customizable.

**Comment by payam-zahedi** [comment]
Hey @tomassasovsky,

I guess you can do it just right now. You can set the default behavior in the `ToastificationConfig` class. You can check the doc in here:

[ToastificationConfig](https://github.com/payam-zahedi/toastification?tab=readme-ov-file#globaldefault-configuration)

The `itemWidth` is the thing that you need. 

You can also use it in a specific page.

**Comment by payam-zahedi** [comment]
Example:

``` dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Toastification',
      builder: (context, child) {
        return ToastificationConfigProvider(
          config: const ToastificationConfig(
            margin: EdgeInsets.fromLTRB(0, 16, 0, 110),
            alignment: Alignment.center,
            itemWidth: 440,
            animationDuration: Duration(milliseconds: 500),
          ),
          child: child!,
        );
      },
    );
  }
}
```

**Comment by payam-zahedi** [comment]
@tomassasovsky Is that what you need?

Can we close the Issue

**Comment by tomassasovsky** [comment]
That's problematic for when you're dealing with resizable screens, since you can't re-configure the width of the item.

**Comment by rmahmadkhan** [comment]
there is no minimum width. when text is very short, we see empty space on side
