### ISSUE TITLE
should also be able to set the width of an toast item through showCustom function 

### ISSUE THREAD

**Issue by prashant-singh-maersk** [payam-zahedi/toastification#93]
**Describe the solution you'd like**
Currently we can set the width of toast item only through ToastificationConfigProvider, 
can we also have width argument in the show and showCustom function which would set the width of the item

**Additional context**
I am trying to make a reusable flutter toast widget, I don't want to ask user to wrap  in a  ToastificationConfigProvider

**Comment by payam-zahedi** [comment]
Hey @prashant-singh-maersk 
Can you provide a simple code for better understanding?

**Comment by payam-zahedi** [comment]
If you want to set width to your toast via showCustom 

Why you are not using SizedBox ?

**Comment by prashant-singh-maersk** [comment]
> Hey @prashant-singh-maersk Can you provide a simple code for better understanding?
something like 
```
toastification.showCustom(
      context: context,
      alignment: position,
      width: 500,
      .....
);
```

**Comment by prashant-singh-maersk** [comment]
> If you want to set width to your toast via showCustom
> 
> Why you are not using SizedBox?

We can not set the width using the sized box, because the package is setting the width of the overlay entry through ToastificationConfigProvider or ToastificationConfig by default, 
so no matter what width we set through widgets, it will never be more than the width of the overlay entry.

**Comment by payam-zahedi** [comment]
you want something like this right?

![image](https://github.com/payam-zahedi/toastification/assets/47558577/467985a7-f5e9-4d25-9011-3d0c4e5e8cff)



example code:
``` dart 
 toastification.showCustom(
    builder: (BuildContext context, ToastificationItem holder) {
      return Align(
        alignment: Alignment.centerRight,
        child: Container(
          color: Colors.blue,
          height: 100,
          width: 300,
          margin: const EdgeInsets.all(8),
        ),
      );
    },
  );

```

**Comment by prashant-singh-maersk** [comment]
> you want something like this right?
> 
> ![image](https://private-user-images.githubusercontent.com/47558577/316229651-467985a7-f5e9-4d25-9011-3d0c4e5e8cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTg5MDEsIm5iZiI6MTcxMTM1ODYwMSwicGF0aCI6Ii80NzU1ODU3Ny8zMTYyMjk2NTEtNDY3OTg1YTctZjVlOS00ZDI1LTkwMTEtM2QwYzRlNWU4Y2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA5MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOWQwZWU5ZTI3MjAxMTMxNTE2ZGY5NDNiYTNjNTc1ZTkyNzE4ZDcwOGFiNTg1N2NmNzA3OTVmZTY0MzIxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fubkd9pkwBNBkPEjKexpxzkt7Yc2sx7G1PznBljAP3w)
> 
> example code:
> 
> ```dart
>  toastification.showCustom(
>     builder: (BuildContext context, ToastificationItem holder) {
>       return Align(
>         alignment: Alignment.centerRight,
>         child: Container(
>           color: Colors.blue,
>           height: 100,
>           width: 300,
>           margin: const EdgeInsets.all(8),
>         ),
>       );
>     },
>   );
> ```

I understand,
this would work if your width is less than 400. (The above example has a width 300) 
but I'll not be able to set the width to more than 400

**Comment by payam-zahedi** [comment]
Did you use config provider?

With the config provider, you can set the width of the whole overlay

I think this is the thing that you want

https://github.com/payam-zahedi/toastification?tab=readme-ov-file#globaldefault-configuration

**Comment by payam-zahedi** [comment]
@prashant-singh-maersk Maybe I need to rename `itemWidth` in the config Provider to make it more readable.

**Comment by prashant-singh-maersk** [comment]
@payam-zahedi 
I appreciate your patience. 
I am aware of the config provider, yes we can set the width using config provider. 
but wanted to know if we can give a width option in the showCustom function itself,

eg: alignment can be given in config provider and showCustom function, showCustom property one takes the priority

same way can we have a width option in showCustom function ?

**Comment by payam-zahedi** [comment]
I guess there is a miss understanding here 

we have itemWidth in the config file that we use to set the width of the animated list that we have in our overlay 

and you can use show custom and set some width to your toast

these are different 

we can not change the width of the animated list every time that you want to build a toast 

imagine if you could set some width in the show custom method 
it would change all the width of the toasts

**Comment by payam-zahedi** [comment]
I guess we can close this issue for now 

but, feel free to ask any question about it
