### ISSUE TITLE
Is it still being maintained and will a new version be released on pub?

### ISSUE THREAD

**Issue by laterdayi** [payam-zahedi/toastification#95]
Is it still being maintained and will a new version be released on pub?

**Comment by payam-zahedi** [comment]
Yes for sure.

I was very busy last weeks, but I will try to add new version as soon as possible.

**Comment by frederikstonge** [comment]
In the meantime, you can reference the git repository directly from your pubspec:

```yaml
toastification:
    git: https://github.com/payam-zahedi/toastification
```

**Comment by payam-zahedi** [comment]
The new version is published on pub, you can use it now 

https://pub.dev/packages/toastification
