### ISSUE TITLE
ToastificationManager._createNotificationHolder (package:toastification/src/core/toastification_manager.dart:193:45)

### ISSUE THREAD

**Issue by blackpink7** [payam-zahedi/toastification#99]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
Some widgets require an Overlay widget ancestor for correct operation.
The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
The context from which that widget was searching for an overlay was:
  Navigator-[LabeledGlobalKey<NavigatorState>#cce4f]
#0      Overlay.of.<anonymous closure> (package:flutter/src/widgets/overlay.dart:547:9)
#1      Overlay.of (package:flutter/src/widgets/overlay.dart:550:6)
#2      ToastificationManager._createNotificationHolder (package:toastification/src/core/toastification_manager.dart:193:45)
#3      ToastificationManager.showCustom (package:toastification/src/core/toastification_manager.dart:60:7)
#4      Toastification.showCustom (package:toastification/src/core/toastification.dart:140:20)
#5      Toastification.show (package:toastification/src/core/toastification.dart:245:12)
#6      init<…>

**Comment by payam-zahedi** [comment]
The error is saying that it can not find the Navigator in your app

Do you use Material App in your project?

how do you use toastification? Where do you get the context?

**Comment by payam-zahedi** [comment]
I will close this for now. 

Feel free to open it if you had the same issue

**Comment by blackpink7** [comment]
thanks i did it

**Comment by blackpink7** [comment]
> I will close this for now.
> 
> Feel free to open it if you had the same issue

thanks i did it
